### ISSUE TITLE
Error: Cannot find module 'js-csp

### ISSUE THREAD

**Issue by stepheneb** [loadedsith/JavascriptHinter.tmbundle#1]
seems like a missing development/build dependency

adding:

```    "js-csp": "1.0.x"```

to package.json removed this error after making and installing into textmate

```
internal/modules/cjs/loader.js:550 throw err;^ Error: Cannot find module 'js-csp' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15) at Function.Module._load (internal/modules/cjs/loader.js:475:25) at Module.require (internal/modules/cjs/loader.js:598:17) at require (internal/modules/cjs/helpers.js:11:18) at Object. (/Users/stephen/Library/Application Support/TextMate/Pristine Copy/Bundles/JavascriptHinter.tmbundle/Support/plugins-loader.js:1:77) at Module._compile (internal/modules/cjs/loader.js:654:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10) at Module.load (internal/modules/cjs/loader.js:566:32) at tryModuleLoad (internal/modules/cjs/loader.js:506:12) at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by loadedsith** [comment]
Hi stepheneb, 

Thank you for filing this issue. I've updated the package.json in https://github.com/loadedsith/JavascriptHinter.tmbundle/commit/5d3e61c3d30a68c6054274f06a2bfac569cf8c4c

I'd be happy to help you troubleshoot any more issues, if/when they arise. I'd even accept feature requests, within reason.

**Comment by stepheneb** [comment]
Thanks!

Ages ago I did some work on an ancestor of this package (when it download jshint instead of using node packages). I'll have some more questions shortly, after I get some work done using the version you forked from ;-)
